name: CI build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run Tests
        run: ./mvnw test
      - name: Package
        run: ./mvnw package -DskipTests
      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t codingwulf/invento-hub-product-service .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image
        run: docker push codingwulf/invento-hub-product-service
